### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by zwj2017-NK** [fmind/euphony#2]
How to use Euphony efficiently？How the program read android files？I ran code with command ,which as follows:
java -jar euphony.jar -e output-dir/ -r reports.vt -CPEO
but I failed.
Exception in thread "main" java.lang.NullPointerException
	at clojure.lang.Numbers.ops(Numbers.java:1013)
	at clojure.lang.Numbers.gte(Numbers.java:233)
	at euphony.commands.parser$parse.invokeStatic(parser.clj:110)
	at euphony.commands.parser$parse.doInvoke(parser.clj:103)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at euphony.tasks$with_parse_mapping_BANG_.invokeStatic(tasks.clj:56)
	at euphony.tasks$with_parse_mapping_BANG_.invoke(tasks.clj:53)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at clojure.core$comp$fn__4727.invoke(core.clj:2460)
	at euphony.tasks$make_BANG_.invokeStatic(tasks.clj:235)
	at euphony.tasks$make_BANG_.invoke(tasks.clj:233)
	at euphony.core$_main.invokeStatic(core.clj:57)
	at euphony.core$_main.doInvoke(core.clj:51)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at euphony.core.main(Unknown Source)

**Comment by fmind** [comment]
Hello,

Could you post some lines from your reports.vt file ?

From the output, it seems the file cannot be parsed properly.

**Comment by zwj2017-NK** [comment]
![2018-02-27 16-33-35](https://user-images.githubusercontent.com/29697744/36718264-1d00817a-1bdc-11e8-92e8-6621254f6290.png)

**Comment by zwj2017-NK** [comment]
The reports.vt file derives from the source code.

**Comment by fmind** [comment]
Thank to your issue, I found a bug that occurs when dataset is very small, like in the example case.

I've pushed a new version in target/uberjar. It works on my environment. Could you please try it ?

**Comment by zwj2017-NK** [comment]
Thanks a lot. I have a suggestion that if the program can get the data of virustotal report from serveral files, instead of only one.For example, the program can get the input from special directory which includes all virustotal report.

**Comment by fmind** [comment]
This is an interesting use case, but I think GNU/Linux commands can handle it already.

For instance, you can use `cat` to concatenate several files prior to Euphony execution:
```
cat reports/*.json > reports.vt
java -jar euphony.jar -e output-dir/ -r reports.vt -CPEO
```

Or if you want to concatenate them during Euphony execution:
```
java -jar euphony.jar -e output-dir/ -r <(cat reports/*.json) -CPEO
```

**Comment by zwj2017-NK** [comment]
Thank you for your lastest answer.
I tried to run this program with a virustotal file which includes over 280,000 records 6 days ago,but it is still running.The setting of our server is as follows:  Memory --- 94 GB , CPU --- 16 cores.
I want to know how long the program will take. Many thanks.

**Comment by fmind** [comment]
The maximum number of records I had to process was 1 million. It took 8 hours to process the reports with my local machine (8 cores, 32 GB or ram with the default settings).

The longest step is the parsing stage. You can tune the time it takes by changing the max-turn parameter (-m). Try with 2 or 3.

**Comment by zwj2017-NK** [comment]
java -jar  euphony.jar  -e -m 2 ./output-dir/  -r  reports_new.vt -CPEO，
The long-time problem remains, and without  an experimental results.

**Comment by fmind** [comment]
You can send me an email including our reports, I will see if it takes as much time on my computer.

**Comment by hs048** [comment]
hai, I have the same problem, 100 sample from virusshare in output-dir, please help me why is it still an error?.
![euphony error](https://user-images.githubusercontent.com/73588020/97426972-0f9d2600-194f-11eb-81b0-99a085bd1b44.PNG)
![euphony error2](https://user-images.githubusercontent.com/73588020/97426981-1166e980-194f-11eb-9d48-adc321f1600f.PNG)

**Comment by sbkorke** [comment]
I am facing this problem for long time. I tried but failed. please can anyone help????

C:\euphony-master>java -jar euphony.jar -e ./ -r mal_vt_reports.vt -CPEO
Exception in thread "main" java.lang.AssertionError: Assert failed: (not-empty labels)
        at euphony.tasks$with_parse_mapping_BANG_.invokeStatic(tasks.clj:54)
        at euphony.tasks$with_parse_mapping_BANG_.invoke(tasks.clj:54)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at clojure.core$comp$fn__4727.invoke(core.clj:2460)
        at euphony.tasks$make_BANG_.invokeStatic(tasks.clj:236)
        at euphony.tasks$make_BANG_.invoke(tasks.clj:234)
        at euphony.core$_main.invokeStatic(core.clj:59)
        at euphony.core$_main.doInvoke(core.clj:53)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at euphony.core.main(Unknown Source)

**Comment by hlyu-hit** [comment]
> 

> I am facing this problem for long time. I tried but failed. please can anyone help????
> 
> C:\euphony-master>java -jar euphony.jar -e ./ -r mal_vt_reports.vt -CPEO Exception in thread "main" java.lang.AssertionError: Assert failed: (not-empty labels) at euphony.tasks$with_parse_mapping_BANG_.invokeStatic(tasks.clj:54) at euphony.tasks$with_parse_mapping_BANG_.invoke(tasks.clj:54) at clojure.core$comp$fn__4727.invoke(core.clj:2460) at clojure.core$comp$fn__4727.invoke(core.clj:2460) at clojure.core$comp$fn__4727.invoke(core.clj:2460) at clojure.core$comp$fn__4727.invoke(core.clj:2460) at clojure.core$comp$fn__4727.invoke(core.clj:2460) at clojure.core$comp$fn__4727.invoke(core.clj:2460) at euphony.tasks$make_BANG_.invokeStatic(tasks.clj:236) at euphony.tasks$make_BANG_.invoke(tasks.clj:234) at euphony.core$_main.invokeStatic(core.clj:59) at euphony.core$_main.doInvoke(core.clj:53) at clojure.lang.RestFn.applyTo(RestFn.java:137) at euphony.core.main(Unknown Source)

Have you ever solved that? I have encountered the same issue.
I use `vt-py` to get json files（`get_json()`）, and I found that it's doesn't match the program input.
